hooks:
  update_modules:
    post:
      - npm run build
  gh_pages:
    pre:
      - npm run doc

config:
  git_user_name: CircleCI
  git_user_email: circleci@example.com
  npm_update_depth: 3
  version_prefix: v
  create_branch: false
  npm_shrinkwrap: false
  create_gh_pages: true
  gh_pages_dir: doc
circle:
  machine:
    node:
      version: 6.3.0
