---
env:
  node: true
  commonjs: true
  es6: true
extends: airbnb
installedESLint: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
  - flow-vars
  - import
rules:
  brace-style: [error, stroustrup, { "allowSingleLine": true }]
  comma-dangle: off
  max-len:
    - error
    - 120
    - ignoreTrailingComments: true
    - ignoreUrls: true
  no-unused-vars: warn
  no-unneeded-ternary: error
  no-nested-ternary: warn
  no-lonely-if: warn
  no-irregular-whitespace:
    - error
    - skipTemplates: true
  no-confusing-arrow: 0
  no-constant-condition:
    - error
    - checkLoops: false
  new-cap:
    - error
    - capIsNew: false
  yoda:
    - error
    - never
    - onlyEquality: true
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prefer-const: warn

  flowtype/require-return-type: 0

  flowtype/space-after-type-colon:
    - 1
    - always
  flowtype/space-before-type-colon:
    - 1
    - never
  flowtype/type-id-match:
    - 1
    - "^([A-Z][a-z0-9]+)+$"

  flow-vars/define-flow-type: 1
  flow-vars/use-flow-type: 1
  no-duplicate-imports: 0
  import/no-duplicates: 1
  import/extensions: 1
  react/jsx-filename-extension: 0
  react/require-extension: 0
  react/jsx-no-bind: 0

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
  import/core-modules: [ electron ]
